project:
  type: website

website:
  title: "Seismic Monitoring CO~2~ Storage"
  sidebar:
    background: primary
    logo: "images/digitaltwin.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://flexie.github.io/EAS-4803-8803-CCS/
        text: GitHub
      # - icon: cloud-fill
        # href: https://rstudio.cloud/spaces/237799
        # text: RStudio Cloud
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: goals.qmd
        text: Goals    
      - href: docker.qmd
        text: Docker      
      # - href: schedule.qmd
      #   text: Schedule
      # - href: seminar.qmd
      #   text: Seminar        
      - href: project.qmd
        text: Project 
      # - href: references.qmd  
format:
  html:
    theme: cosmo
   # css: styles.css
    toc: true

bibliography: references.bib
license: CC BY



