---
title: "Seismic Monitoring CO~2~ Storage"
subtitle: "Seismic Monitoring CO~2~ Storage - EAS 4803 - EAS 8803 - FH"
---

## Course overview

*Carbon Capture and Storage (CCS) is widely considered as a key scalable net-negative CO~2~ emission technology to help combat climate change. The course covers the Basics of [Geological Carbon Storage](outline.md), its [Design & Scale Up](outline.md), and its [Seismic Monitoring](outline.md). Aside from reviewing the geophysical challenges and computational aspects of monitoring Geological Carbon Storage, the course also addresses societal impact of this technology. Its (perceived) risk will be discussed by weighting the risk of doing something, by injecting CO~2~ underground, against doing nothing.*

## Class meetings

| Meeting | Location                             | Time                    |
|---------|--------------------------------------|-------------------------|
| Lecture | Ford Environmental Sci & Tech, L1116 | Mon & Wed 3:30 - 4:45PM |

## Teaching team

| Name | Office hours | Location |
|-------------------------------|-----------------------|------------------|
| [Felix J. Herrmann](mailto:felix.herrmann@gatech.edu) (Instructor) | TBD | Zoom |
| [Haoyun (Jason) Li](mailto:hli853@gatech.edu) (TA) | TBD | Zoom |

## Access to Piazza

Students are encouraged to post their questions on [Piazza](https://piazza.com/class/m48xmhumtiuhv/), which will be monitored by [Haoyun (Jason) Li](mailto:mailto:hli853@gatech.edu).